allowBuilds:
  '@parcel/watcher': false
  core-js: false
  core-js-pure: false
  es5-ext: false
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - metadata-abstract-ui@2.0.41-beta.1
  - metadata-core@2.0.41-beta.1
  - metadata-dhtmlx@2.0.41-beta.1
  - metadata-pouchdb@2.0.41-beta.1
  - metadata-react@2.0.41-beta.1
  - metadata-redux@2.0.41-beta.1
